name:                tortue
version:             0.1.0.0
github:              "githubuser/tortue"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tortue#readme>

dependencies:
- base >= 4.7 && < 5
# For debugging, tests and benchmarks
- aeson
- aeson-pretty
- bytestring
- scientific
- text
- unordered-containers
- vector

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -O2

library:
  source-dirs: src

executables:
  tortue-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -optl-s # Strip file (enabled by default on stack)
    - -dynamic # Link RTS dynamically (saves >700KB)
    dependencies:
    - tortue

tests:
  tortue-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tortue
